### ISSUE TITLE
Transferring repository to https://github.com/webgpu/samples

### ISSUE THREAD

**Issue by austinEng** [webgpu/webgpu-samples#226]
We'd like to transfer this repository to https://github.com/webgpu/samples so it's in a shared community organization and not under my personal github account :)

Creating this issue to seek any feedback/comments from the various non-Google contributors. Thank you for your contributions!
 - @onsummer 
 - @munrocket 
 - @HypnosNova
 - @webglzhang 
 - @inokawa
 - @rvadhavk
 - @lukehesluke
 - @frguthmann
 - @ponitka
 
I'll wait for a period of about two weeks, and if there are no strong objections, I'll transfer the repo on February 17, 2023.

**Comment by HypnosNova** [comment]
That's a great idea.
And my pr: https://github.com/austinEng/webgpu-samples/pull/204 
I think this is a good sample but no one cr. It would be better merge into master before transfer repository to webgpu/samples

**Comment by hepp** [comment]
This is great news!
Thank you for this, I'm looking forward to seeing a thriving platform for contributions.

If interested - I have created several new examples at https://www.wgsl.dev/, which could be ported over.

Also below are a couple ideas on what I might be working on next / or what we could potentially add here.

- Example of Video 3D Plane
- Example of Quad raymarching 
- Example of Light with a simplified deferred setup

**Comment by austinEng** [comment]
The transfer is complete!
