### ISSUE TITLE
Does it really matter to use a very strict GPUBufferUsage  ?

### ISSUE THREAD

**Issue by tlecoz** [webgpu/webgpu-samples#234]
Hi 

I'm refactoring my framework based on webgpu. 
The first time, I started from the first sample and added features one step after the other without any visibility about how things works and was doable but I was "blocked" after ComputeBoids  because you start to use multiple bindgroups. 

I rebuild everything and I 'm not following the samples anymore, I now know what I want to do and I'm questioning the "ping-pong" structure used with computePipelines samples

 Is it really better to alternate between a bindgroup with
GPUBufferUsage.STORAGE | GPUBufferUsage.COPY_SRC 
and another one with
GPUBufferUsage.STORAGE | GPUBufferUsage.COPY_DST  

 instead of just using a single bindgroup with GPUBufferUsage.STORAGE | GPUBufferUsage.COPY_SRC | GPUBufferUsage.COPY_DST ? 
 
 Is it a big deal to use a flexible GPUBufferUsage ?
 Because it's a big deal to implement a strict one compared to a flexible one, that's why I want to know if it worth the time 😅 
 
 
 EDIT : in my current case, I'm using a computePipeline alone and I'm realizing it's a specific case  : the "ping pong structure" is not required because of "copyBufferToBuffer". 
 
 Anyway, I'm interested to know if it's really important to be as strict as possible or if it only concerns those who create AAA games ? 
 
 
 EDIT 2 : in the sample "computeBoidss" , you can use one buffer with a "read" accessMode and another with "read-write" access mode because you use an "auto" layout for the pipeline so buffer access mode is not well defined in the layout and it's possible to swap the buffers without breaking the layout.  But if you used a well defined layout for the pipeline, would you be forced to use a "read-write" access mode for both buffers in order to be able to alternate them during the "ping pong" process ?  
 
 ------ 
 
 Actually, I have the exact same question with GPUShaderStageFlags 
 
 it it a big deal to use GPUShaderStage.VERTEX | GPUShaderStage.FRAGMENT | GPUShaderStage.COMPUTE for every uniforms ? 
 
 Does it really has an impact of the performance to be strict  ? If yes, what kind of impact ? Is it like 0.01% faster or 5% faster ? :)

**Comment by kainino0x** [comment]
webgpu-samples "issues" are for bug reports about the samples. Please post questions in a discussion section, either here or in the specification repository (https://github.com/gpuweb/gpuweb/discussions) or StackOverflow (though I don't know how many answerers are there).

There are some answers to this question buried in the history of the gpuweb repository somewhere, but not easily findable. Feel free to re-post as a gpuweb discussion if you'd like.

The short answer to all of these questions is that it's highly dependent on your hardware and your workload. You'll need to benchmark if you want to know the true answer. Generally speaking, COPY_SRC and COPY_DST have negligible cost, the others are harder to answer.

**Comment by tlecoz** [comment]
"Please post questions in a discussion section, either here or in the specification repository (https://github.com/gpuweb/gpuweb/discussions)" 

I'm sorry, I didn't aware about this page 😅 

"The short answer to all of these questions is that it's highly dependent on your hardware and your workload. You'll need to benchmark if you want to know the true answer. Generally speaking, COPY_SRC and COPY_DST have negligible cost, the others are harder to answer." 

Thank you

**Comment by kainino0x** [comment]
No worries!
