### ISSUE TITLE
The deferred renderer example has a validation error with maxColorAttachmentBytesPerSample.

### ISSUE THREAD

**Issue by Kangz** [webgpu/webgpu-samples#237]
```
Total color attachment bytes per sample (40) exceeds maximum (32) with formats ([ TextureFormat::RGBA32Float TextureFormat::RGBA32Float TextureFormat::BGRA8Unorm ]).
 - While validating fragment state.
 - While calling [Device].CreateRenderPipeline([RenderPipelineDescriptor]).
```

**Comment by 823984418** [comment]
This seems to be related to https://github.com/gpuweb/gpuweb/pull/3367 .

But I never seem to be able to request a higher limit.

**Comment by shrekshao** [comment]
If not able to request a higher limit, to fix the sample, I think one easier change is to use 'float16x4' and 'RGBA16Float' for the second render target (normal)

(32 bytes per sample for color attachment seems to be quite strict for any float target then)
