### ISSUE TITLE
GPUDevice.createRenderPipeline: 'layout' member of GPUPipelineDescriptorBase is not an object

### ISSUE THREAD

**Issue by IamLupo** [webgpu/webgpu-samples#248]
When i run the Hello Triangle example i get the following error:
`TypeError: GPUDevice.createRenderPipeline: 'layout' member of GPUPipelineDescriptorBase is not an object.`
 
I wonder if i did something wrong?

Browser: Firefox Nightly 113.0a1 (2023-04-07) (64-bits)

about:config settings:
dom.webgpu.enabled = true
gfx.webrender.all = true

about:support state:
Web API: WebGPU (dom.webgpu.enabled)	true

**Comment by kainino0x** [comment]
Firefox does not yet quite fully support the WebGPU standard. I believe [`"auto"` layout](https://gpuweb.github.io/gpuweb/#default-pipeline-layout) support is one of their outstanding gaps.

**Comment by IamLupo** [comment]
> Firefox does not yet quite fully support the WebGPU standard. I believe [`"auto"` layout](https://gpuweb.github.io/gpuweb/#default-pipeline-layout) support is one of their outstanding gaps.

Thank you for taking the time and react! I will be patient for firefox so far ;) On chrome it worked like a charm! :D
