### ISSUE TITLE
We may want to use `wgpu-matrix` instead of `gl-matrix` for webgpu

### ISSUE THREAD

**Issue by shrekshao** [webgpu/webgpu-samples#253]
Originally from https://github.com/shrekshao/webgpu-typescript-starter/issues/1#issue-1679755248

>    1. gl-matrix makes GL matrixes for perspective, ortho, and frustum. Not WebGPU matrixes
>    1. gl-matrix makes 3x3 matrices that are incompatible with WebGPU (WebGPU: 12 floats (padded), WebGL 9 floats)
>    suggestion [wgpu-matrix](https://github.com/greggman/wgpu-matrix)

I agree as an "official" sample, it is better to use a "more correct" solution to avoid any further confusion.
(For 1) Even gl-matrix has [`perspectiveZO`](https://github.com/toji/gl-matrix/blob/master/src/mat4.js#L1585), it is less straight-forward.

If we decide to make this shift, I can take care of the change in samples.

**Comment by austinEng** [comment]
Sounds great to me to use a matrix library that is catered specifically to WebGPU.
