### ISSUE TITLE
shadowMapping: wgpu-matrix 2.x changed mat4.lookAt()

### ISSUE THREAD

**Issue by microaaron** [webgpu/webgpu-samples#268]
https://github.com/webgpu/webgpu-samples/blob/0e1529da031b68e2ddf84a3a59651f2a4a987a11/src/sample/shadowMapping/main.ts#L367

https://github.com/webgpu/webgpu-samples/assets/16946786/e8455e05-4a92-4fa3-9c3b-98d4e4bce883

**Comment by magcius** [comment]
In v1, wgpu-matrix's lookAt computes the inverse of what is commonly called lookAt in other matrix libraries. This was changed for v2. So this is correct for now, but would become a hazard when we upgrade.

https://github.com/greggman/wgpu-matrix/issues/2

**Comment by microaaron** [comment]
> In v1, wgpu-matrix's lookAt computes the inverse of what is commonly called lookAt in other matrix libraries. This was changed for v2. So this is correct for now, but would become a hazard when we upgrade.
> 
> [greggman/wgpu-matrix#2](https://github.com/greggman/wgpu-matrix/issues/2)

Thanks. #271 is working on upgrading the samples to 2.x.
