### ISSUE TITLE
Can add a sample program for rendering YUV using webgpu?

### ISSUE THREAD

**Issue by luojinghui** [webgpu/webgpu-samples#275]
【Feature】
The YUV data has been converted into Uint8Array. Next, I want to render it to the canvas through webgpu, but after trying, it fails.  Have any good ideas or sample programs?

**Comment by kainino0x** [comment]
I think you might want to make a VideoFrame out of the YUV data and then importExternalTexture (in spec, but only shipped behind Origin Trial in chrome right now) or copyExternalImageToTexture (not in spec yet, will be soon)

**Comment by luojinghui** [comment]
https://codepen.io/jkqbnbyh-the-flexboxer/pen/GRwoxwK?editors=0010

**Comment by SUDOCS** [comment]
@luojinghui https://codepen.io/sudocs/pen/gOZwdVG

**Comment by luojinghui** [comment]
> @luojinghui https://codepen.io/sudocs/pen/gOZwdVG

thanks👍
