### ISSUE TITLE
Remove files in `public/img`

### ISSUE THREAD

**Issue by ben-clayton** [webgpu/webgpu-samples#321]
There are a bunch of images in [`public/img`](https://github.com/webgpu/webgpu-samples/tree/main/public/img), which are also duplicated in [`public/assets/img`](https://github.com/webgpu/webgpu-samples/tree/main/public/assets/img).

I believe this was caused by a race between the PRs: https://github.com/webgpu/webgpu-samples/pull/313 and https://github.com/webgpu/webgpu-samples/pull/310.

I believe the files in  [`public/img`](https://github.com/webgpu/webgpu-samples/tree/main/public/img) are not in use, and should be removed.

**Comment by cmhhelgeson** [comment]
Just wanted to check in and see if this issue still needed addressing.
