### ISSUE TITLE
Cornell box sample does not appear to be compliant with the WGSL specification

### ISSUE THREAD

**Issue by mwyrzykowski** [webgpu/webgpu-samples#337]
As discussed in https://github.com/gpuweb/gpuweb/issues/4415 and https://github.com/gpuweb/gpuweb/issues/4291, the following line from the Cornell box sample:
https://github.com/webgpu/webgpu-samples/blob/main/src/sample/cornell/common.wgsl#L111C31-L111C46
```
 return f32(rnd.x ^ rnd.y) / f32(0xffffffff);
```
should probably be a compiler error, because the current version of the WGSL specification does not allow conversion of 0xffffffff to be passed to f32(...), it would overflow and result in an error.

While the working group decides on the correct behavior in the specification, could we change line https://github.com/webgpu/webgpu-samples/blob/main/src/sample/cornell/common.wgsl#L111C31-L111C46 to the following please?
```
 return f32(rnd.x ^ rnd.y) / 4294967295.0;
```

That way we don't have one of the reference samples out of compliance with the specification. cc @ben-clayton who authored the sample - thank you for writing it too :)

**Comment by ben-clayton** [comment]
Thank you for raising this. This is a pretty bad divergence between Tint and the spec.

I replied on https://github.com/gpuweb/gpuweb/issues/4415#issuecomment-1850152484.

I'd hope that we'd change the spec to allow this, but I'm not strongly opposed to changing this temporarily.

**Comment by mwyrzykowski** [comment]
Issue is resolved by https://github.com/webgpu/webgpu-samples/issues/337 and we can continue discussion in https://github.com/gpuweb/gpuweb/issues/4415
