### ISSUE TITLE
Video decoding using WebCodecs API 

### ISSUE THREAD

**Issue by sasmaster** [webgpu/webgpu-samples#342]
Hi guys. I am a bit confused by video upload samples. [Here ](https://chromestatus.com/feature/5078348864159744) it is stated that webgpu api now can work with Webcodecs API via external texture. However, reading the source code of those samples I see no webcodecs API used. The only related chunk I see is VideoFrame object. Can you please confirm that chrome supports interaction of WebGPU with Webcodecs API?

**Comment by greggman** [comment]
The samples do no show every possible usage of WebGPU. They are just a random collection of samples.

Here are some of the conformance tests

https://gpuweb.github.io/cts/standalone/?runnow=1&q=webgpu:web_platform,external_texture,video:importExternalTexture,sample:videoName=%22four-colors-vp8-bt601.webm%22;sourceType=%22VideoElement%22;dstColorSpace=%22srgb%22
https://gpuweb.github.io/cts/standalone/?runnow=1&q=webgpu:web_platform,external_texture,video:importExternalTexture,sample:videoName=%22four-colors-h264-bt601.mp4%22;sourceType=%22VideoElement%22;dstColorSpace=%22srgb%22
https://gpuweb.github.io/cts/standalone/?runnow=1&q=webgpu:web_platform,external_texture,video:importExternalTexture,compute:videoName=%22four-colors-vp8-bt601.webm%22;sourceType=%22VideoElement%22;dstColorSpace=%22srgb%22
https://gpuweb.github.io/cts/standalone/?runnow=1&q=webgpu:web_platform,external_texture,video:importExternalTexture,compute:videoName=%22four-colors-h264-bt601.mp4%22;sourceType=%22VideoElement%22;dstColorSpace=%22srgb%22

**Comment by greggman** [comment]
VideoFrame is the WebCodecs api

https://w3c.github.io/webcodecs/#videoframe-interface

https://developer.mozilla.org/en-US/docs/Web/API/WebCodecs_API

What were you hoping to find?

**Comment by sasmaster** [comment]
I was hoping to find an example of interaction with Webcodecs API (decoder or encoder), but no problem, I see that VideoFrame is part of the API. Thanks!

**Comment by kainino0x** [comment]
This has been added by the videoUploadingWebCodecs sample #247
