### ISSUE TITLE
Directional light won't cast shadow when positioned right atop the scene

### ISSUE THREAD

**Issue by pietrovismara** [webgpu/webgpu-samples#353]
If you change [this line](https://github.com/webgpu/webgpu-samples/blob/main/src/sample/shadowMapping/main.ts#L294) to

```
const lightPosition = vec3.fromValues(0, 100, 0);
```

no shadow is projected:
<img width="449" alt="image" src="https://github.com/webgpu/webgpu-samples/assets/9806520/da2c3d5d-b7f6-4ae7-9d7c-ceac50a952c7">

As a novice in graphics, I wonder is this a bug or an edge case with the ortographic projection of the light?

**Comment by ben-clayton** [comment]
The next line is:
https://github.com/webgpu/webgpu-samples/blob/f4b46f00da0b8107ef95876a144ec38ef9cceda7/src/sample/shadowMapping/main.ts#L295

When you change `lightPosition` to `[0, 100, 0]`, the view direction (`origin` to `lightPosition`) becomes parallel to the `upVector`. In this situation, there's an ambiguity in which way the returned matrix should be orientated.

If you want  `lightPosition` directly above the origin, you need to change the `upVector` to some other normalized vector.

**Comment by pietrovismara** [comment]
Got it, thanks!
