### ISSUE TITLE
Load samples in iframes?

### ISSUE THREAD

**Issue by kainino0x** [webgpu/webgpu-samples#355]
Right now it's a bit tricky to read and write the sample code in the GitHub repository, because it has some odd bits that allow React to load the page into the SPA correctly. A long time ago @austinEng and I talked about having each sample be its own page loaded in an iframe, so they wouldn't have to do that. I think we should still do this.

**Comment by kainino0x** [comment]
I'd at least like to get rid of the `if (!pageState.active) return;` thing but maybe `makeSample` part can stay the same since it's pretty out-of-the-way.

**Comment by greggman** [comment]
I started trying to separate the samples from the sample browser but Austin seemed to want it to somehow generate separate samples without changing the code. As in code-gen separate samples. I wasn't sure what the point of that would be. I thought the point was mostly to make the samples standalone (no React, no connection to the framework), that way, like the three.js example browser, it's easy to look at any sample in isolation.  On the other hand, there's the issue that all (most?) current samples are in typescript and so need a build step. Making per example build steps is more work.

**Comment by austinEng** [comment]
Well, I wanted to keep them authorable in Typescript, and have plain JS code available. Ripping out the React quirks I would definitely like to do.

**Comment by greggman** [comment]
Ok, I will look into seeing if I can separate them.

**Comment by greggman** [comment]
done I think
