### ISSUE TITLE
Sample(s) for hidpi, ResizeObserver, and fullscreen

### ISSUE THREAD

**Issue by kainino0x** [webgpu/webgpu-samples#356]
We should have a sample that demonstrates correct usage of ResizeObserver to create canvases which are hidpi, resize-responsive, and fullscreenable. It should:
- Show a checkerboard pattern to demonstrate the pixel size
- Correctly handle both changing browser scale and changing canvas size
- Let the user easily play with resizing by putting a resize handle on the canvas container div
- Have a fullscreen button (perhaps fullscreening not just the canvas but a div containing some trivial HTML like a text overlay)

See also #249 about using hidpi canvases in more samples, which perhaps this sample should supersede.

**Comment by kainino0x** [comment]
It could possibly also demonstrate CSS `image-rendering` options.
The sample image from the CSS spec is a nice test case for scaling-related stuff, could use it.
https://drafts.csswg.org/css-images/#example-30207ff9

**Comment by greggman** [comment]
done
