### ISSUE TITLE
Some samples don't work on Edge 122 with Intel Iris Plus graphics

### ISSUE THREAD

**Issue by birdboat00** [webgpu/webgpu-samples#361]
Some samples (tested: helloTriangle, cubemap, texturedCube) don't show anything (helloTriangle, cubemap) or show a black cube without any texture (texturedCube)

OS: Windows 11 23H2
GPU: Intel Iris Plus in 10th Gen Core i5 (Surface Pro 7) with latest drivers
Browser: Latest stable Edge 122 with No Flags set

**Comment by kainino0x** [comment]
Does it work in the equivalent Chrome 122? If so, this sounds like an Edge bug, and it should be filed with Edge. (please link to a bug report here if you file one)

If it doesn't work in Chrome either then it sounds like a Chromium issue - please file an issue on crbug.com
