### ISSUE TITLE
Link to or embed other known samples

### ISSUE THREAD

**Issue by kainino0x** [webgpu/webgpu-samples#362]
- @toji
  - https://spookyball.com/
  - https://toji.github.io/webgpu-metaballs/
  - https://toji.github.io/webgpu-clustered-shading/
  - https://toji.github.io/pristine-grid-webgpu/
  - https://toji.github.io/webgpu-bundle-culling/
- I know there are others but not off the top of my head

It may become possible to embed these once #355 is done (though idk if github.io allows COEP)

**Comment by greggman** [comment]
Put up a PR. It works. Thoughts?

It's not clear to me if linking to external examples a good thing or not. I think Brandon's examples are great but I once you set the example of linking to external examples then everyone will want their sample included. Maybe that's a good thing though?

Note: the PR also tries to grab the source which works for spookyball but there's many files (didn't list them all. Just wanted to see if it worked). We could not show any source, or show something else (link to article/github).

@kainino0x @toji @beaufortfrancois @Kangz @austinEng

**Comment by kainino0x** [comment]
> It's not clear to me if linking to external examples a good thing or not. I think Brandon's examples are great but I once you set the example of linking to external examples then everyone will want their sample included. Maybe that's a good thing though?

I was thinking that's probably a good thing. Right now we have people wanting to add samples to this repo which means we have to take on some maintenance burden. Easier if we can link to them. The number of links will probably get pretty big though, so maybe external samples would be a separate section in the sidebar.

That said, it occurs to me that linked samples could change underneath us - disappear, break, or even get replaced with malicious content.
A middle ground could be to accept samples as Git submodules so we're pinned to a revision?

**Comment by greggman** [comment]
I think the samples changing is not a big deal. People will file an issue and we can fix or remove.

I don't think we don't want to rehost them (which might include having to build and maintain their build infra). I suppose you meant to pin their live repo (eg gh-pages) as a submodule but that would mean having to review updates often if they're iterating on their sample.

**Comment by toji** [comment]
I agree that we don't want to re-host any content. It does open us up for some minor unexpected breakage, but the maintenance burden otherwise is going to be pretty high and driven by external forces.

**Comment by greggman** [comment]
done?
