### ISSUE TITLE
Can't run Hello Triangle sample on Linux

### ISSUE THREAD

**Issue by zilun-wang** [webgpu/webgpu-samples#390]
I successfully ran the Hello Triangle Demo before, but I found I couldn't run it anymore today.
I tested on the Linux Platform and used Chromium (Version 116.0.5793.0).
I have enabled the [#enable-unsafe-webgpu](chrome://flags/#enable-unsafe-webgpu) flag and I ran the Chromium with this command "chrome --no-sandbox --enable-features=Vulkan".

When I accessed the Hello Triangle sample's webpage, the triangle did not show up. And I got the following console logs:

`Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'interest-cohort'.
main.ts:21 Uncaught TypeError: Failed to execute 'createRenderPipeline' on 'GPUDevice': Failed to read the 'fragment' property from 'GPURenderPipelineDescriptor': Failed to read the 'entryPoint' property from 'GPUProgrammableStage': Required member is undefined.
    at main.ts:21:25`
  
Could you please help me address this issue?

**Comment by greggman** [comment]
Do you this flag on?

chrome://flags/#enable-unsafe-webgpu

**Comment by beaufortfrancois** [comment]
Default entry points to shader modules are available in Chrome 121. See https://developer.chrome.com/blog/new-in-webgpu-121?hl=en#default_entry_points_to_shader_modules
You'll need to update your Chromium browser (version 116) to version 121.
