### ISSUE TITLE
Textures not working in certain samples

### ISSUE THREAD

**Issue by cmhhelgeson** [webgpu/webgpu-samples#394]
Textured Cube:

![image](https://github.com/webgpu/webgpu-samples/assets/62450112/7799197e-0215-420a-9dc5-00f828da45fd)

Render Bundles:

![image](https://github.com/webgpu/webgpu-samples/assets/62450112/fac5966b-102a-4ed1-ba3c-7c1ef31329e7)

Image Blur:

![image](https://github.com/webgpu/webgpu-samples/assets/62450112/6ad985af-7aa1-4f7e-9ff6-09e8b33df29c)

Normal map also fails to display textures as well.

Running on an Asus Zenbook with a 13th Gen Intel(R) Core(TM i9-13900H 2.60 GHz, with Intel(R) Iris(R) Xe Graphics.

**Comment by greggman** [comment]
* Do you get any errors in the JavaScript console?
* What browser? What version?
* Can you attach the output of about:gpu if Chrome?
* Do they work in another browser? TexturedCube works for me in Firefox Nightly
* If it's a chrome bug, file a bug at crbug.com

They work for me on Window 11 NVidia, and Mac M1 in Chrome 122

![2024_03_11-22_52_17_chrome_83](https://github.com/webgpu/webgpu-samples/assets/234804/d55c8fd1-4507-4101-a93b-42d225497526)
![2024_03_11-22_52_38_chrome_84](https://github.com/webgpu/webgpu-samples/assets/234804/1c45ad8e-6e42-47b8-8aba-371fe6879014)
![2024_03_11-22_53_15_chrome_85](https://github.com/webgpu/webgpu-samples/assets/234804/b1e557e0-25e9-4380-bfec-bb26d2733a63)

**Comment by cmhhelgeson** [comment]
The issue seems uniform across browsers, and there are no console errors. Chrome version is 122.0.6261.112. Here is the about.gpu output
[about-gpu-2024-03-12T15-57-42-577Z.txt](https://github.com/webgpu/webgpu-samples/files/14575329/about-gpu-2024-03-12T15-57-42-577Z.txt)

**Comment by cmhhelgeson** [comment]
I think this is either an issue with the browser or my machine, I'm getting tons of weird issues around fragment shaders.
