### ISSUE TITLE
ViewSource button appears non-functional on Chrome Version 122.0.6261.112 (Official Build) (arm64)

### ISSUE THREAD

**Issue by mwyrzykowski** [webgpu/webgpu-samples#399]
I see this when I click the 'ViewSource' button on Chrome Version 122.0.6261.112 (Official Build) (arm64) from https://webgpu.github.io/webgpu-samples/?sample=bundleCulling

Is that expected?
<img width="1184" alt="Screenshot 2024-03-12 at 12 55 09 PM" src="https://github.com/webgpu/webgpu-samples/assets/105083895/c50e725d-c97c-431f-b595-92b8583ed0fc">

**Comment by beaufortfrancois** [comment]
FYI DevTools JavaScript console says "Refused to frame 'https://github.com/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'none'"."

**Comment by beaufortfrancois** [comment]
I've opened https://github.com/toji/webgpu-bundle-culling/pull/1 to fix the issue.

**Comment by mwyrzykowski** [comment]
The same issue exists on https://webgpu.github.io/webgpu-samples/?sample=pristineGrid - should I make a new issue for that?
