### ISSUE TITLE
Web Workers

### ISSUE THREAD

**Issue by ottoville** [webgpu/webgpu-samples#41]
According to WEBGPU spec, WEBGPU objects such as buffers should be able to move between worker threads.
Should there be example for doing that?

**Comment by kainino0x** [comment]
AFAIK there are no implementations of that part of the spec yet. (Chrome does not implement it.) It's still in flux because the design hasn't been proven out yet. I'm sure a sample will appear once someone starts implementing it.

**Comment by kainino0x** [comment]
This is not in the spec anymore. We'll eventually add a sample whenever it gets added to the spec.
