### ISSUE TITLE
When uploadvideo type is ogv, importExternalTexture report error

### ISSUE THREAD

**Issue by z4122** [webgpu/webgpu-samples#417]
In VideoUploading example, if I change video to an ogv video, it will throw an error. If the type is webm or mp4, it will work fine.

![image](https://github.com/webgpu/webgpu-samples/assets/13222615/84d0a6ef-a10c-4150-8eb3-64d8a3184b7c)

![image](https://github.com/webgpu/webgpu-samples/assets/13222615/75bea1b9-f376-4608-bdf8-2dcc443d001f)

**Comment by beaufortfrancois** [comment]
The following [Chromium source code](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/modules/webgpu/external_texture_helper.cc;l=160;drc=3a1e3af23a522fa002253636be7d50256924ddfb
) shows that `GetCurrentFrameThenUpdate()` returns null. I'm not sure why though that's the case for an ogv file...

```cpp
ExternalTextureSource GetExternalTextureSourceFromVideoElement(
    HTMLVideoElement* video,
    ExceptionState& exception_state) {
  ...
  
  if (auto* wmp = video->GetWebMediaPlayer()) {
    source.media_video_frame = wmp->GetCurrentFrameThenUpdate();
    source.video_renderer = wmp->GetPaintCanvasVideoRenderer();
  }
  
  if (!source.media_video_frame) {
    exception_state.ThrowDOMException(DOMExceptionCode::kOperationError,
                                      "Failed to import texture from video "
                                      "element that doesn't have back "
                                      "resource.");
```

@Djuffin and @dalecurtis may be able to help us understand what is causing this issue.

**Comment by greggman** [comment]
Chrome bugs should probably be discussed on the chrome issue site? 

https://crbug.com/

**Comment by dalecurtis** [comment]
Only VP8 in ogg is now supported: https://chromestatus.com/feature/5158654475239424
