### ISSUE TITLE
Don't throw on unknown messages

### ISSUE THREAD

**Issue by brendan-duncan** [webgpu/webgpu-samples#420]
In main.ts window.addEventListener, an exception is thrown for unknown messages.

With my WebGPU Inspector debugger, https://github.com/brendan-duncan/webgpu_inspector, window messages are used to communicate from the injected scripts to the extension content_script.

When the window event handler in main.ts gets the inspector messages, it throws an exception. Leaving unknown messages alone makes it a lot easier for chrome extension debuggers to work.

**Comment by greggman** [comment]
We can remove the throw unknown message but, expecting some random page to not throw on an unknown message seems like it would make many pages not work in the debugger.  Is there some other way to pass the message?

**Comment by greggman** [comment]
I think this will wrap `onmessage` and `addEventListener`

```js
const GlobalCtor = globalThis.constructor;

const GlobalPropertyDescriptors = Object.getOwnPropertyDescriptors(globalThis);

const isOurMessage = e => e.data.sig === 'webgpu_inspector';
const listenerToWrapperFn = new WeakMap();

function makeWrapper(listener) {
  const wrapper = function(event) {
    if (isOurMessage(event)) {
      // do something with our message
      console.log('got message from us', event.data);
    } else {
      return listener.call(this, event);
    }
  };
  listenerToWrapperFn.set(listener, wrapper);
  return wrapper;
}

Object.defineProperty(globalThis, 'onmessage', {
  get() {
    const listener = GlobalPropertyDescriptors.onmessage.get.call(this);
    return listenerToWrapperFn.get(listener) ?? listener;
  },
  set(listener) {
    GlobalPropertyDescriptors.onmessage.set.call(this, makeWrapper(listener));
  }
});

GlobalCtor.prototype.addEventListener = (function(origFn) {
  return function(name, listener, ...args) {
    listener = name === 'message' ? makeWrapper(listener) : listener;
    return origFn.call(this, name, listener, ...args);
  }

})(GlobalCtor.prototype.addEventListener);

GlobalCtor.prototype.removeEventListener = (function(origFn) {
  return function(name, listener, ...args) {
    listener = listenerToWrapperFn.get(listener) ?? listener;
    return origFn.call(this, name, listener, ...args);
  };
})(GlobalCtor.prototype.removeEventListener);
```

[example](https://jsgist.org/?src=d2db1342c33d51fca249bd9595a182a6)

**Comment by brendan-duncan** [comment]
Yeah, maybe I need to go back to the drawing board on that one.

**Comment by brendan-duncan** [comment]
I'll close this issue. I think a CustomEvent is probably the better choice for this rather than message. Thanks for setting me straight.
