### ISSUE TITLE
The "find" functionality is broken on desktop. Makes it hard to navigate the code.

### ISSUE THREAD

**Issue by Tomycj** [webgpu/webgpu-samples#426]
The find function (Ctrl+F) doesn't work properly in the section that shows the code in the webgpu samples, at least on Chrome for desktop. For some reason it often doesn't find all matches within the code). The same section has its own search function, but it sticks to the bottom, which makes it almost useless since it gets out of reach once it jumps to a match that's out of view.

**Comment by greggman** [comment]
Can you post a video of the issue?

This is what I see on my Mac

https://github.com/webgpu/webgpu-samples/assets/234804/b2d88be0-78a6-42cd-8edb-8652850ee103

(ps: used handbreak to take it from 38meg to 3meg)

**Comment by Tomycj** [comment]
Thank you for the detailed reply!

Notice how the browser's find function was unable to find all matches (it misses "device" on line 216). It seems to only be able to find those that are roughly visible on screen, so it works a little better for words with a lot of matches since switching between them reveals new text to find new matches on.

https://github.com/webgpu/webgpu-samples/assets/51275588/db771be4-bbd8-49cd-b046-1e5f3020d291

The behavior on my end is the same, except I can't (or don't know how to) automatically move between matches without having to go back down to the finder controls. That capability (or the controls staying fixed on the screen, like the browser's) would make it much more comfortable to browse the code. Btw, how do you manage to view the page in dark colors?

Thank you.

**Comment by greggman** [comment]
> Btw, how do you manage to view the page in dark colors?

For me, I go into my OS and set it to dark mode

* [MacOS](https://support.apple.com/guide/mac-help/use-a-light-or-dark-appearance-mchl52e1c2d2/m)
* [Windows](https://support.microsoft.com/en-us/windows/change-colors-in-windows-d26ef4d6-819a-581c-1581-493cfcc005fe)

Or you can set your browser to dark mode separate from your OS

* Chrome: https://support.google.com/chrome/answer/9275525
* Firefox: https://support.mozilla.org/en-US/kb/change-website-appearance-settings-firefox

**Comment by greggman** [comment]
#428
