### ISSUE TITLE
computeBoids setting wrong index for vertex buffer?

### ISSUE THREAD

**Issue by mkvenkit** [webgpu/webgpu-samples#436]
Hello,

In main.ts, you have:

`passEncoder.setVertexBuffer(1, spriteVertexBuffer);
`
https://github.com/webgpu/webgpu-samples/blob/fa7b0221782fa9ba2b6a516187260b2424b8ae99/sample/computeBoids/main.ts#L277

But in sprite.wgsl, the user-defined inputs to the vertex shader are:

```
fn vert_main(
  @location(0) a_particlePos : vec2f,
  @location(1) a_particleVel : vec2f,
  @location(2) a_pos : vec2f
) -> VertexOutput {
```

Isn't `spriteVertexBuffer` associated with `a_pos`, and hence have a vertex buffer index of 2 instead of 1? If that's correct, shouldn't there also be a separate call to set the vertex buffer for `a_particleVel` in the render pipeline? 

Thanks for any clarification!

**Comment by greggman** [comment]
`a_pos` has an `attribute` location 2. Which buffers supply values to attributes is defined in the pipeline description

```ts
const renderPipeline = device.createRenderPipeline({
  layout: 'auto',
  vertex: {
    module: spriteShaderModule,
    buffers: [
      {
        // instanced particles buffer
        arrayStride: 4 * 4,
        stepMode: 'instance',
        attributes: [
          {
            // instance position
            shaderLocation: 0,
            offset: 0,
            format: 'float32x2',
          },
          {
            // instance velocity
            shaderLocation: 1,
            offset: 2 * 4,
            format: 'float32x2',
          },
        ],
      },
      {
        // vertex buffer
        arrayStride: 2 * 4,
        stepMode: 'vertex',
        attributes: [
          {
            // vertex positions
            shaderLocation: 2,
            offset: 0,
            format: 'float32x2',
          },
        ],
      },
    ],
  },
```

Above we see the first to attributes (`shaderLocation: 0` and `shaderLocation: 1` are getting their info from vertexBuffer 0 (because its element 0 of the `buffers` array), and `shaderLocation: 2` is gettings its data from vertexBuffer 1 ((because its element 1 of the `buffers` array).

**Comment by mkvenkit** [comment]
> because its element 1 of the buffers array

Ah, that was my confusion. Vertex buffer slot vs. location.

Thanks for the quick response!
