### ISSUE TITLE
Add proper credits for msdfgen

### ISSUE THREAD

**Issue by quinton-ashley** [webgpu/webgpu-samples#447]
The MSDF Text Rendering sample is a fantastic demo! I really appreciate it. 😄
https://webgpu.github.io/webgpu-samples/?sample=textRenderingMsdf

But, I think referring to msdfgen, both on the website and in the example code, solely as Don McCurdy's tool isn't giving enough credit to the original author of the technique and the C++ msdfgen tool that Don McCurdy's [msdf-bmfont-xml](https://github.com/soimy/msdf-bmfont-xml) tool uses internally. Don's addition was working out how to efficiently pack characters into one image and make a make json atlas for it.

The MSDF technique was published in ["Shape Decomposition for Multi-channel Distance Fields"](https://dspace.cvut.cz/bitstream/handle/10467/62770/F8-DP-2015-Chlumsky-Viktor-thesis.pdf) and [msdfgen](https://github.com/Chlumsky/msdfgen) was created by Chlumsky Viktor.

Also if anyone is interested, recently Chlumsky authored his own C++ tool for font atlas generation, [msdf-atlas-gen](https://github.com/Chlumsky/msdf-atlas-gen), last updated in June 2024. It seems that over the years he expanded on his previous technique to create 4 channel "MTSDF" files, which utilize the alpha channel to store "Soft effects": "effects that use true distance, such as glows, rounded outlines, or simplified shadows". While I haven't used it myself it sounds incredible! Would be cool to have an MTSDF example in webgpu too. 😅

**Comment by toji** [comment]
That's a great point, thanks for bringing it up! I'll try to get a CL that updates the description to link out to these references in the next day or so.
