### ISSUE TITLE
WebGPU Samples page cannot load due to missing `main.js`

### ISSUE THREAD

**Issue by iwoplaza** [webgpu/webgpu-samples#466]
The previously available file at [https://webgpu.github.io/webgpu-samples/main.js](https://webgpu.github.io/webgpu-samples/main.js) is missing after a recent deployment.

![image](https://github.com/user-attachments/assets/4383e371-bf6e-43ef-ab48-338feaadc91b)

**Comment by iwoplaza** [comment]
Could be due to the recent requirement bump to Node v20. Maybe a redeploy would help?

![image](https://github.com/user-attachments/assets/e7d9bb5d-0ec6-4f5b-93dd-9926ed4ae87c)

**Comment by beaufortfrancois** [comment]
FWIW I've just merged https://github.com/webgpu/webgpu-samples/commit/79485ded481e57610c977b94937f9764f84fd6ff and it didn't help.
I guess something is broken. @greggman Can you have a look?

**Comment by kainino0x** [comment]
Looks OK now, guessing it was fixed by #465?
